name: Setup

inputs:
  python-version:
    required: false
    default: '3.11'
  torch-version:
    required: false
    default: '2.3.0'
  cuda-version:
    required: false
    default: cpu
  full_install:
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ inputs.python-version }}
        check-latest: true
        cache: pip
        cache-dependency-path: |
          requirements.txt

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        pip install torch==${{ inputs.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version == 'nightly' }}
      run: |
        pip install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash

    - name: Install Pytorch Geometric ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      run: |
        pip install torch-geometric
        pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
        pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
        pip install torch-cluster -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html        
        pip install pyg-lib -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
      shell: bash

    - name: Install pyg-lib
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        pip uninstall -y pyg-lib
        pip install --no-index pyg-lib -f https://data.pyg.org/whl/nightly/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
      shell: bash

    - name: Install extension packages
      if: ${{ inputs.full_install == 'true' && inputs.torch-version != 'nightly' && (runner.os != 'macOS' || inputs.torch-version == '2.3.0') }}
      run: |
        pip install scipy==1.13.1
        pip install --no-index --upgrade torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-${{ inputs.torch-version }}+${{ inputs.cuda-version }}.html
      shell: bash
