name: Tests

on:
  release:
    branches:
        - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup packages
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
      - name: Install package with pip
        run:
          pip install . -v
        shell: bash
      - name: Test with pytest
        run: |
          cd tests
          python -m unittest discover . 'test*.py'
        shell: bash
